# -*- coding: utf-8 -*-
"""BJMissouri.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OqwT9L6ELVMJhfSbzRRe_xjVWoed7Ok4
"""

import random
class Card:
    rank = ''
    suit = ''
    # Initializer. First slot is rank, second slot is suit. Suit will not be important until our stretch goals.
    # Write the rank as 1 character, not as a number. For 2-9, write '2', '3',..., or '9'
    # For Ace, write 'A'
    # For Jack, Queen, King, I would prefer that you write 'J', 'Q', 'K'
    # For 10, I would prefer that you write 'T'
    # Use 'C' for cut card
    def __init__(self, r, s=''):
        self.rank = r
        self.suit = s
    def __str__(self):
        return str(self.rank) + str(self.suit)
    # Use this to get the card's value for blackjack. Just call this function, it's called in Hand
    def val(self):
        match(self.rank):
            # Tens
            case 'T'|'J'|'Q'|'K':
                return 10
            # Ace is yielded as 1, 11 case handled in hand.val()
            case 'A':
                return 1
            case '2':
                return 2
            case '3':
                return 3
            case '4':
                return 4
            case '5':
                return 5
            case '6':
                return 6
            case '7':
                return 7
            case '8':
                return 8
            case '9':
                return 9
            case _:
                return 0

class Shoe:
    # Holds all the cards
    shoe = []
    # Is false when the cut card comes out
    play = True

    def __init__(self, decks=1, shuffle=True, cards=None, penMin=.7, penMax=.8):
        self.play = True
        # If you want to fill with a premade deck (not standard deck), set cards to a specific value when calling
        if cards is not None:
            self.shoe = cards
        else:
            self.shoe = []
        # Otherwise, ignore cards and fill it with standard decks
            for r in ['A','2','3','4','5','6','7','8','9','T','J','Q','K']:
                for s in ['c','d','h','s']:
                    # Puts decks in
                    for x in range(0,decks):
                        c = Card(r,s)
                        self.shoe.append(c)
            # print(str(self))
        # Shuffles the deck by default
        if shuffle:
            random.shuffle(self.shoe)
        l = len(self.shoe)
        # Inserts cut card. When the cut card is drawn, this denotes the last hand
        c = Card('C')
        # Puts it in somewhere between penMin & penMax of the deck.
        # penMax should never be 1, and probably shouldn't be inputted as higher than .9
        # penMin should never be 0, and probably shouldn't be inputted as lower than .5
        self.shoe.insert(random.randrange(int(l*penMin), int(l*penMax)),c)
        # print(str(self))

    # Should work like the standard array toString representation
    def __str__(self):
        return '['+', '.join(str(x) for x in self.shoe)+']'

    def deal(self,fromTop):
        # Deal a card
        c = self.shoe.pop(fromTop)
        # If it's a valid card, return it
        if (c.val() > 0):
            return c
        # If it's not, (cut card), deal the next card
        self.play = False
        return self.deal(fromTop)

class Hand:
    cards = []
    deck = None
    double = False
    hasBeenSplit = False
    isSoft = False
    def __init__(self, cards=None, deck=None, hasBeenSplit=False):
        self.cards = cards if cards is not None else []
        self.deck = deck
        self.double = False
        self.hasBeenSplit = hasBeenSplit
        self.isSoft = False
    # Returns blackjack value of the hand
    def val(self):
        v = 0
        hasAce = False
        self.isSoft = False  # reset each call
        for x in self.cards:
            v += x.val()
            if x.val() == 1:
                hasAce = True
        if hasAce and v <= 11:
            v += 10
            self.isSoft = True
        return v
    # Adds a card to the hand. Use for hit, double, and split
    def addCard(self,fromTop):
        self.cards.append(self.deck.deal(fromTop))
    def __str__(self) -> str:
       return '['+', '.join(str(x) for x in self.cards)+']'

# Superclass for all bots
class Bot:
  def __init__(self):
    pass
  # Always plays 1 hand by default
  def handNum(self, game):
    return 1
  # Not very good at making decisions, very bad strategy
  def decision(self, options, hand, dealerHand):
    return random.choice(options)

# Bot that plays like the dealer. Not much better than random
class DealerBot(Bot):
  def __init__(self):
    super().__init__()

  def handNum(self, game):
    return 1

  def decision(self, options, hand, dealerHand):
    return 'h' if hand.val() < 17 or (hand.val()==17 and self.game.h17) else 's'

# Plays "basic strategy". Slightly losing but pretty decent
class BasicStrategyH17Bot(Bot):
  def __init__(self, das):
     # Covers hard totals between 9 and 16. Unless it's a double/split, above is a stand and everything below is a hit
     # I'm sure there are better ways to compress this but oh well. Maybe a 2D array
     self.HardChart = {
     (16,2):'s',(16,3):'s',(16,4):'s',(16,5):'s',(16,6):'s',(16,7):'h',(16,8):'h',(16,9):'h',(16,10):'h',(16,11):'h',
     (15,2):'s',(15,3):'s',(15,4):'s',(15,5):'s',(15,6):'s',(15,7):'h',(15,8):'h',(15,9):'h',(15,10):'h',(15,11):'h',
     (14,2):'s',(14,3):'s',(14,4):'s',(14,5):'s',(14,6):'s',(14,7):'h',(14,8):'h',(14,9):'h',(14,10):'h',(14,11):'h',
     (13,2):'s',(13,3):'s',(13,4):'s',(13,5):'s',(13,6):'s',(13,7):'h',(13,8):'h',(13,9):'h',(13,10):'h',(13,11):'h',
     (12,2):'h',(12,3):'h',(12,4):'s',(12,5):'s',(12,6):'s',(12,7):'h',(12,8):'h',(12,9):'h',(12,10):'h',(12,11):'h',
     (12,2):'h',(12,3):'h',(12,4):'s',(12,5):'s',(12,6):'s',(12,7):'h',(12,8):'h',(12,9):'h',(12,10):'h',(12,11):'h',
     (11,2):'d',(11,3):'d',(11,4):'d',(11,5):'d',(11,6):'d',(11,7):'d',(11,8):'d',(11,9):'d',(11,10):'d',(11,11):'d',
     (10,2):'d',(10,3):'d',(10,4):'d',(10,5):'d',(10,6):'d',(10,7):'d',(10,8):'d',(10,9):'d',(10,10):'h',(10,11):'h',
     (9,2):'h',(9,3):'d',(9,4):'d',(9,5):'d',(9,6):'d',(9,7):'h',(9,8):'h',(9,9):'h',(9,10):'h',(10,11):'h'}
     # Covers soft totals between 13 and 19
     self.SoftChart = {
     (19,2):'s',(19,3):'s',(19,4):'s',(19,5):'s',(19,6):'D',(19,7):'s',(19,8):'s',(19,9):'s',(19,10):'s',(19,11):'s',
     (18,2):'D',(18,3):'D',(18,4):'D',(18,5):'D',(18,6):'D',(18,7):'s',(18,8):'s',(18,9):'h',(18,10):'h',(18,11):'h',
     (17,2):'h',(17,3):'d',(17,4):'d',(17,5):'d',(17,6):'d',(17,7):'h',(17,8):'h',(17,9):'h',(17,10):'h',(17,11):'h',
     (16,2):'h',(16,3):'h',(16,4):'d',(16,5):'d',(16,6):'d',(16,7):'h',(16,8):'h',(16,9):'h',(16,10):'h',(16,11):'h',
     (15,2):'h',(15,3):'h',(15,4):'d',(15,5):'d',(15,6):'d',(15,7):'h',(15,8):'h',(15,9):'h',(15,10):'h',(15,11):'h',
     (14,2):'h',(14,3):'h',(14,4):'h',(14,5):'d',(14,6):'d',(14,7):'h',(14,8):'h',(14,9):'h',(14,10):'h',(14,11):'h',
     (13,2):'h',(13,3):'h',(13,4):'h',(13,5):'d',(13,6):'d',(13,7):'h',(13,8):'h',(13,9):'h',(13,10):'h',(13,11):'h',}
     # Always splitting Aces and 8s, represented in decision
     self.SplitHands = {(18,2),(18,3),(18,4),(18,5),(18,6),(18,8),(18,9), (14,2),(14,3),(14,4),(14,5),(14,6),(14,7), (12,3),(12,4),(12,5),(12,6), (6,4),(6,5),(6,6),(6,7), (4,4),(4,5),(4,6),(4,7)}
     if(das):
       # If game allows DAS, add a few more hands to split that only split with DAS allowed
       self.SplitHands = self.SplitHands.union({(12,2),(8,5),(8,6),(6,2),(6,3),(4,2),(4,3)})
       # Surrender on these hands
     self.SurHands = {(16,9),(16,10),(16,11),(15,10)}

  def handNum(self, game):
    return 1

  def decision(self, options, hand, dealerHand):
    # Source: https://www.blackjackapprenticeship.com/blackjack-strategy-charts/
    if (not hand.isSoft):
      hardTuple = (hand.val(), dealerHand.val())
      # If it's in surrenderHands, then surrender
      if hardTuple in self.SurHands and 'l' in options:
        return 'l'
      # If it's a split hand, split
      if 'v' in options:
        if hand.val()==16 or hardTuple in self.SplitHands:
          return 'v'
      # Otherwise stand on 17 or more
      if hand.val()>16:
        return 's'
      # Otherwise hit on 8 or less
      if hand.val()<9:
        return 'h'
      # Otherwise find the play in the HardChart (fallback: stand on 17+, else hit)
      if hardTuple not in self.HardChart:
          return 's' if hand.val() >= 17 else 'h'
      p = self.HardChart[hardTuple]
      if p == 'd':
        if 'd' in options:
          return 'd'
        else:
          return 'h'
      return p

    else:
      # Stand on soft 20
      if(hand.val()==20):
        return 's'
      # Split Aces, otherwise hit if not available to split (RSA off or something)
      if(hand.val()==12):
        if 'v' in options:
          return 'v'
        else:
          return 'h'
      key = (hand.val(), dealerHand.val())
      if key not in self.SoftChart:
          return 's' if hand.val() >= 18 else 'h'
      p = self.SoftChart[key]
      match(p):
        case 'D':
          if 'd' in options:
            return 'd'
          else:
            return 's'
        case 'd':
          if 'd' in options:
            return 'd'
          else:
            return 'h'
        case _:
          return p

# A trained card counter could reasonably do this to potentially a small profit
class SimpleHiLoCountingNoDev(BasicStrategyH17Bot):
  def __init__(self, das, maxHands):
    super().__init__(das)
    self.maxHands = maxHands
# Plays as many hands as possible at a true count of 1 or more (true count = running Count/decks remaining)
  def handNum(self, game):
    rCount = 0
    for c in self.game.deck.cards:
      if c.val()==1 or c.val()==10:
        rCount +=1
      elif c.val()>1 or c.val()<7:
        rCount -=1
    return self.maxHands if rCount*52/len(self.game.deck.cards)>=1 else 1

class Game:
  # Number of bets "brought" to the casino
  sbalance = 1000
  balance = 1000
  # True if the dealer hits on soft 17, False if stands on soft 17
  h17=True
  # By default blackjack pays 3:2
  blackjack=1.5
  # Re-Split Aces
  rsa=True
  # Double after split
  das=True
  surrender=True
  # For a 6:5 sim, set blackjack to 1.2
  def __init__(self, balance=1000,h17=True,blackjack=1.5,rsa=True,das=True,surrender=True):
    self.sbalance = balance
    self.balance = balance
    self.h17 = h17
    self.blackjack=blackjack
    self.rsa=rsa
    self.das=das
    self.surrender=surrender

  # Call this to play in the terminal
  def play(self, decks=1, shuffle=True, cards=None, penMin=.7, penMax=.8, bot=None):
    while(True):
      print("\n\nNew shoe starting\n\n")
      shoe = Shoe(decks=decks, shuffle=shuffle, cards=cards,penMin=penMin, penMax=penMax)
      print(shoe)
      # Place bets
      while(shoe.play):
        print("Balance: "+ str(self.balance)+"\n")
        print("How many hands to play?")
        if bot is not None:
          print("Bot says "+str(bot.handNum(self))+"\n")
        h = input()
        while(not h.isnumeric or self.balance < int(h) or int(h)<0):
          h = input()
        h = int(h)
        # Enter 0 to end session or "Wong out"
        if h==0:
          print("\n\nSession over. Total profit: "+str(self.balance-self.sbalance))
          return
        self.balance -= h

        # Deal cards
        hands = []
        dealerHand = Hand(deck=shoe,cards=[])
        for i in range(int(h)):
          hands.append(Hand(deck=shoe,cards=[]))
          hands[i].addCard(0)
        dealerHand.addCard(0)
        for i in range(int(h)):
          hands[i].addCard(0)
          print("Hand "+str(i+1)+": "+str(hands[i])+"\n")
        print("Dealer: ",str(dealerHand)+"\n")

        # On dealer blackjack, with a ten face up, end the hand
        if(dealerHand.val()==10):
          if(shoe.shoe[0].val()==1):
            print(str(shoe.deal(0))+"\n",)
            print("\nDealer blackjack\n")
            for x in hands:
            # If player doesn't also have blackjack, they receive nothing, but if they do, they get their money back
              if(x.val()==21):
                self.balance +=1
            continue


        # On dealer blackjack with an ace face up, end the hand
        elif(dealerHand.val()==11):
          if(shoe.shoe[0].val()==10):
            # Insurance Implementation (stretch goal) would go here
            print(str(shoe.deal(0))+"\n",)
            print("\nDealer blackjack\n")
            for x in hands:
              if(x.val()==21):
                self.balance +=1
            continue


        # Otherwise, start playing
        print("\nKey\nHit: h\nStand: s\nDouble: d\nSplit: v\nSurrender: l\n")
        # Play each hand
        i=0
        # This stores preemptively ended hands
        p = 0
        while i< len(hands):
          # Handles case where cards can be split
          if(len(hands[i].cards)==1):
            hands[i].addCard(1)
          # Initial options are hit, stand, and double (unless it's a split hand and no double after split)
          options = ['h','s']
          if (not(self.das and hands[i].hasBeenSplit)):
            options.append('d')
          # If surrender is offered, it is added
          if(self.surrender and not hands[i].hasBeenSplit and len(hands[i].cards)==2):
            options.append('l')
          # If the cards are the same rank, split is added. If they're both aces rsa is disabled
          if(hands[i].cards[0].rank==hands[i].cards[1].rank and not(not self.rsa and hands[i].cards[1].val()==1)):
            options.append('v')

          # Play each hand, removing hands that bust or make natural 21
          while(len(options)>0):
            print("Hand "+str(i+1+p)+": "+str(hands[i].val())+"\n"+str(hands[i])+"\n")
            if(hands[i].val()>21):
                print("\nBust\n")
                hands.remove(hands[i])
                i -= 1
                p+=1
                options = []
                break

            # If the hand has 21, stop playing
            elif(hands[i].val()==21):
                options = []
                if(len(hands[i].cards)==2):
                  # If it's a natural 21, pay it out immediately (dealer doesn't have blackjack in this branch)
                  print("Blackjack!\n")
                  self.balance += 1 + self.blackjack
                  p += 1
                  hands.remove(hands[i])
                  i -= 1
                # Fixed an issue where getting 21 softlocks you
                break

            # Otherwise, get input
            print("Options are: " + str(options) + "\n")
            if bot is not None:
              print("Bot says "+str(bot.decision(options,hands[i],dealerHand))+"\n")
            c = input()
            # Failsafe
            while c not in options and len(options)>0:
              c = input()

          # When playing, call addCard(1) since the dealer has the 0 card
            match c:
              # Hit
              case 'h':
                hands[i].addCard(1)
                # print("Hand "+str(i+1)+": "+str(hands[i].val())+"\n")
                options = ['h','s']
              # Stand
              case 's':
                options = []
              # Double (costs 1 bet)
              case 'd':
                hands[i].addCard(1)
                print("Hand "+str(i+1)+": "+str(hands[i].val())+"\n"+str(hands[i])+"\n")
                options = []
                hands[i].double = True
                self.balance -= 1
                if(hands[i].val()>21):
                  print("\nBust\n")
                  hands.remove(hands[i])
                  i-=1
                  p+=1
              # Split (costs 1 bet)
              case 'v':
                hands.insert(i, Hand(deck=shoe,cards=[hands[i].cards.pop(1)]))
                i-=1
                # Plays a new hand, so h is increased
                h += 1
                options = []
                self.balance -= 1
              # Surrender: regain half the bet and end the hand
              case 'l':
                options = []
                self.balance += 0.5
                hands.remove(hands[i])
                i-=1
                p += 1
              # This better not be happening
              case _:
                print("\n\nShit has hit the fan why is this running? You know what, whatever\n\n")
          i+=1

        # Reveal second card after all hands have been played
        dealerHand.addCard(0)
        if(len(hands)>0):
          while(dealerHand.val()<=16 or (dealerHand.val()==17 and self.h17 and dealerHand.isSoft)):
            dealerHand.addCard(0)
        print("\nDealer hand: "+str(dealerHand.val())+"\n"+str(dealerHand))
        if(dealerHand.val()>21):
          print("\nDealer bust, all remaining hands win\n")
          for o in range(len(hands)):
            print("Hand "+str(o+1)+ "wins "+str(4 if hands[o].double else 2)+"\n")
            self.balance += (4 if hands[o].double else 2)
        else:
          for h in range(len(hands)):
            print("Hand "+str(h+1)+":")
            if hands[h].val() > dealerHand.val():
              self.balance += 4 if hands[h].double else 2
              print("Win "+ str(4 if hands[h].double else 2)+"\n")
            elif hands[h].val() < dealerHand.val():
              print("Loss\n")
            else:
              print("Push "+str(2 if hands[h].double else 1)+"\n")
              self.balance += 2 if hands[h].double else 1
        print("\n\nNext hand\n\n")

if __name__ == "__main__":
    g = Game()
    g.play(decks=2, shuffle=True, bot=DealerBot())
